/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class City 
        implements java.io.Serializable {
    private static final long serialVersionUID = -443968681217406619L;
    private String name;
    private String hSCode;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("HS_code")
    public String getHSCode ( ) { 
        return this.hSCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("HS_code")
    public void setHSCode (String value) { 
        this.hSCode = value;
    }
 
}
