/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class CityBuilder {
    //the instance to build
    private City city;

    /**
     * Default constructor to initialize the instance
     */
    public CityBuilder() {
        city = new City();
    }

    public CityBuilder name(String name) {
        city.setName(name);
        return this;
    }

    public CityBuilder hSCode(String hSCode) {
        city.setHSCode(hSCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public City build() {
        return city;
    }
}