/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class CountryBuilder {
    //the instance to build
    private Country country;

    /**
     * Default constructor to initialize the instance
     */
    public CountryBuilder() {
        country = new Country();
    }

    public CountryBuilder name(String name) {
        country.setName(name);
        return this;
    }

    public CountryBuilder countryCode(String countryCode) {
        country.setCountryCode(countryCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Country build() {
        return country;
    }
}