/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CreateO2OShopRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 14052615381461991L;
    private String id;
    private ShopNames shopNames;
    private List<String> shopTypes;
    private List<String> shopCategories;
    private ShopAddresses shopAddresses;
    private List<ShopContact> shopContacts;
    private ShopDetails shopDetails;
    private String shopStatus;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shop_names")
    public ShopNames getShopNames ( ) { 
        return this.shopNames;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shop_names")
    public void setShopNames (ShopNames value) { 
        this.shopNames = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shop_types")
    public List<String> getShopTypes ( ) { 
        return this.shopTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shop_types")
    public void setShopTypes (List<String> value) { 
        this.shopTypes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shop_categories")
    public List<String> getShopCategories ( ) { 
        return this.shopCategories;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shop_categories")
    public void setShopCategories (List<String> value) { 
        this.shopCategories = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shop_addresses")
    public ShopAddresses getShopAddresses ( ) { 
        return this.shopAddresses;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shop_addresses")
    public void setShopAddresses (ShopAddresses value) { 
        this.shopAddresses = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shop_contacts")
    public List<ShopContact> getShopContacts ( ) { 
        return this.shopContacts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shop_contacts")
    public void setShopContacts (List<ShopContact> value) { 
        this.shopContacts = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shop_details")
    public ShopDetails getShopDetails ( ) { 
        return this.shopDetails;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shop_details")
    public void setShopDetails (ShopDetails value) { 
        this.shopDetails = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shop_status")
    public String getShopStatus ( ) { 
        return this.shopStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shop_status")
    public void setShopStatus (String value) { 
        this.shopStatus = value;
    }
 
}
