/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class CreateO2OShopRequestBuilder {
    //the instance to build
    private CreateO2OShopRequest createO2OShopRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateO2OShopRequestBuilder() {
        createO2OShopRequest = new CreateO2OShopRequest();
    }

    public CreateO2OShopRequestBuilder id(String id) {
        createO2OShopRequest.setId(id);
        return this;
    }

    public CreateO2OShopRequestBuilder shopNames(ShopNames shopNames) {
        createO2OShopRequest.setShopNames(shopNames);
        return this;
    }

    public CreateO2OShopRequestBuilder shopTypes(List<String> shopTypes) {
        createO2OShopRequest.setShopTypes(shopTypes);
        return this;
    }

    public CreateO2OShopRequestBuilder shopCategories(List<String> shopCategories) {
        createO2OShopRequest.setShopCategories(shopCategories);
        return this;
    }

    public CreateO2OShopRequestBuilder shopAddresses(ShopAddresses shopAddresses) {
        createO2OShopRequest.setShopAddresses(shopAddresses);
        return this;
    }

    public CreateO2OShopRequestBuilder shopContacts(List<ShopContact> shopContacts) {
        createO2OShopRequest.setShopContacts(shopContacts);
        return this;
    }

    public CreateO2OShopRequestBuilder shopDetails(ShopDetails shopDetails) {
        createO2OShopRequest.setShopDetails(shopDetails);
        return this;
    }

    public CreateO2OShopRequestBuilder shopStatus(String shopStatus) {
        createO2OShopRequest.setShopStatus(shopStatus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateO2OShopRequest build() {
        return createO2OShopRequest;
    }
}