/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class OpenHours 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4603723211274121540L;
    private String sun;
    private String mon;
    private String tue;
    private String wed;
    private String thu;
    private String fri;
    private String sat;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sun")
    public String getSun ( ) { 
        return this.sun;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sun")
    public void setSun (String value) { 
        this.sun = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mon")
    public String getMon ( ) { 
        return this.mon;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mon")
    public void setMon (String value) { 
        this.mon = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tue")
    public String getTue ( ) { 
        return this.tue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tue")
    public void setTue (String value) { 
        this.tue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("wed")
    public String getWed ( ) { 
        return this.wed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("wed")
    public void setWed (String value) { 
        this.wed = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("thu")
    public String getThu ( ) { 
        return this.thu;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("thu")
    public void setThu (String value) { 
        this.thu = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fri")
    public String getFri ( ) { 
        return this.fri;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fri")
    public void setFri (String value) { 
        this.fri = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sat")
    public String getSat ( ) { 
        return this.sat;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sat")
    public void setSat (String value) { 
        this.sat = value;
    }
 
}
