/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class OpenHoursBuilder {
    //the instance to build
    private OpenHours openHours;

    /**
     * Default constructor to initialize the instance
     */
    public OpenHoursBuilder() {
        openHours = new OpenHours();
    }

    public OpenHoursBuilder sun(String sun) {
        openHours.setSun(sun);
        return this;
    }

    public OpenHoursBuilder mon(String mon) {
        openHours.setMon(mon);
        return this;
    }

    public OpenHoursBuilder tue(String tue) {
        openHours.setTue(tue);
        return this;
    }

    public OpenHoursBuilder wed(String wed) {
        openHours.setWed(wed);
        return this;
    }

    public OpenHoursBuilder thu(String thu) {
        openHours.setThu(thu);
        return this;
    }

    public OpenHoursBuilder fri(String fri) {
        openHours.setFri(fri);
        return this;
    }

    public OpenHoursBuilder sat(String sat) {
        openHours.setSat(sat);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OpenHours build() {
        return openHours;
    }
}