/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class RatingBuilder {
    //the instance to build
    private Rating rating;

    /**
     * Default constructor to initialize the instance
     */
    public RatingBuilder() {
        rating = new Rating();
    }

    public RatingBuilder point(String point) {
        rating.setPoint(point);
        return this;
    }

    public RatingBuilder star(String star) {
        rating.setStar(star);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Rating build() {
        return rating;
    }
}