/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ShopAddresses 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4603587379056980473L;
    private String fullAddress;
    private Country country;
    private City city;
    private String district;
    private String postcode;
    private String geolocation;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("full_address")
    public String getFullAddress ( ) { 
        return this.fullAddress;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("full_address")
    public void setFullAddress (String value) { 
        this.fullAddress = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("country")
    public Country getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("country")
    public void setCountry (Country value) { 
        this.country = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("city")
    public City getCity ( ) { 
        return this.city;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("city")
    public void setCity (City value) { 
        this.city = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("district")
    public String getDistrict ( ) { 
        return this.district;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("district")
    public void setDistrict (String value) { 
        this.district = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("postcode")
    public String getPostcode ( ) { 
        return this.postcode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("postcode")
    public void setPostcode (String value) { 
        this.postcode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("geolocation")
    public String getGeolocation ( ) { 
        return this.geolocation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("geolocation")
    public void setGeolocation (String value) { 
        this.geolocation = value;
    }
 
}
