/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class ShopNamesBuilder {
    //the instance to build
    private ShopNames shopNames;

    /**
     * Default constructor to initialize the instance
     */
    public ShopNamesBuilder() {
        shopNames = new ShopNames();
    }

    public ShopNamesBuilder mdefault(String mdefault) {
        shopNames.setDefault(mdefault);
        return this;
    }

    public ShopNamesBuilder th(String th) {
        shopNames.setTh(th);
        return this;
    }

    public ShopNamesBuilder en(String en) {
        shopNames.setEn(en);
        return this;
    }

    public ShopNamesBuilder cn(String cn) {
        shopNames.setCn(cn);
        return this;
    }

    public ShopNamesBuilder jp(String jp) {
        shopNames.setJp(jp);
        return this;
    }

    public ShopNamesBuilder kr(String kr) {
        shopNames.setKr(kr);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ShopNames build() {
        return shopNames;
    }
}