/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ShopContact 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8544476558763947474L;
    private String fullName;
    private String phone;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("full_name")
    public String getFullName ( ) { 
        return this.fullName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("full_name")
    public void setFullName (String value) { 
        this.fullName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("phone")
    public String getPhone ( ) { 
        return this.phone;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("phone")
    public void setPhone (String value) { 
        this.phone = value;
    }
 
}
