/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class ShopDetailsBuilder {
    //the instance to build
    private ShopDetails shopDetails;

    /**
     * Default constructor to initialize the instance
     */
    public ShopDetailsBuilder() {
        shopDetails = new ShopDetails();
    }

    public ShopDetailsBuilder shortDescription(String shortDescription) {
        shopDetails.setShortDescription(shortDescription);
        return this;
    }

    public ShopDetailsBuilder fullDescription(String fullDescription) {
        shopDetails.setFullDescription(fullDescription);
        return this;
    }

    public ShopDetailsBuilder openHours(OpenHours openHours) {
        shopDetails.setOpenHours(openHours);
        return this;
    }

    public ShopDetailsBuilder rating(Rating rating) {
        shopDetails.setRating(rating);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ShopDetails build() {
        return shopDetails;
    }
}