/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ShopNames 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5978608169464247463L;
    private String mdefault;
    private String th;
    private String en;
    private String cn;
    private String jp;
    private String kr;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("default")
    public String getDefault ( ) { 
        return this.mdefault;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("default")
    public void setDefault (String value) { 
        this.mdefault = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("th")
    public String getTh ( ) { 
        return this.th;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("th")
    public void setTh (String value) { 
        this.th = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("en")
    public String getEn ( ) { 
        return this.en;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("en")
    public void setEn (String value) { 
        this.en = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cn")
    public String getCn ( ) { 
        return this.cn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cn")
    public void setCn (String value) { 
        this.cn = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("jp")
    public String getJp ( ) { 
        return this.jp;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("jp")
    public void setJp (String value) { 
        this.jp = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("kr")
    public String getKr ( ) { 
        return this.kr;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("kr")
    public void setKr (String value) { 
        this.kr = value;
    }
 
}
