/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ShopDetails 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8328558905389235518L;
    private String shortDescription;
    private String fullDescription;
    private OpenHours openHours;
    private Rating rating;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("short_description")
    public String getShortDescription ( ) { 
        return this.shortDescription;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("short_description")
    public void setShortDescription (String value) { 
        this.shortDescription = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("full_description")
    public String getFullDescription ( ) { 
        return this.fullDescription;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("full_description")
    public void setFullDescription (String value) { 
        this.fullDescription = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("open_hours")
    public OpenHours getOpenHours ( ) { 
        return this.openHours;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("open_hours")
    public void setOpenHours (OpenHours value) { 
        this.openHours = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rating")
    public Rating getRating ( ) { 
        return this.rating;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rating")
    public void setRating (Rating value) { 
        this.rating = value;
    }
 
}
