/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class ShopAddressesBuilder {
    //the instance to build
    private ShopAddresses shopAddresses;

    /**
     * Default constructor to initialize the instance
     */
    public ShopAddressesBuilder() {
        shopAddresses = new ShopAddresses();
    }

    public ShopAddressesBuilder fullAddress(String fullAddress) {
        shopAddresses.setFullAddress(fullAddress);
        return this;
    }

    public ShopAddressesBuilder country(Country country) {
        shopAddresses.setCountry(country);
        return this;
    }

    public ShopAddressesBuilder city(City city) {
        shopAddresses.setCity(city);
        return this;
    }

    public ShopAddressesBuilder district(String district) {
        shopAddresses.setDistrict(district);
        return this;
    }

    public ShopAddressesBuilder postcode(String postcode) {
        shopAddresses.setPostcode(postcode);
        return this;
    }

    public ShopAddressesBuilder geolocation(String geolocation) {
        shopAddresses.setGeolocation(geolocation);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ShopAddresses build() {
        return shopAddresses;
    }
}