/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.models;

import java.util.*;

public class ShopContactBuilder {
    //the instance to build
    private ShopContact shopContact;

    /**
     * Default constructor to initialize the instance
     */
    public ShopContactBuilder() {
        shopContact = new ShopContact();
    }

    public ShopContactBuilder fullName(String fullName) {
        shopContact.setFullName(fullName);
        return this;
    }

    public ShopContactBuilder phone(String phone) {
        shopContact.setPhone(phone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ShopContact build() {
        return shopContact;
    }
}