/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost;

import localhost.controllers.*;
import localhost.http.client.HttpClient;

public class NewSMPShopManagementPlatformClient {
    /**
     * Singleton access to Client controller
     * @return	Returns the APIController instance 
     */
    public APIController getClient() {
        return APIController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Get authentication manager
     */
    public OAuthManager auth() {
        return OAuthManager.getInstance();
    }

    /**
     * Default constructor 
     */     
    public NewSMPShopManagementPlatformClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public NewSMPShopManagementPlatformClient(String oAuthClientId, String oAuthRedirectUri) {
        this();
        Configuration.oAuthClientId = oAuthClientId;
        Configuration.oAuthRedirectUri = oAuthRedirectUri;
    }
}