/*
 * NewSMPShopManagementPlatformLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import localhost.models.*;
import localhost.exceptions.*;
import localhost.APIHelper;
import localhost.Configuration;
import localhost.testing.TestHelper;
import localhost.controllers.APIController;

import com.fasterxml.jackson.core.type.TypeReference;

public class APIControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static APIController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getClient();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Create o2o shop under sprcific brand with basic info
     * @throws Throwable
     */
    @Test
    public void testCreateO2OShop() throws Throwable {
        // Parameters for the API call
        String contentType = "application/json";
        CreateO2OShopRequest body = APIHelper.deserialize("{
  \"id\": \"\",
  \"shop_names\": {
    \"default\": \"เรารักลุงสาขาบางนา\",
    \"th\": \"เรารักลุงสาขาบางนา\",
    \"en\": \"We love uncle @Bangna\",
    \"cn\": \"我們愛叔叔在邦納開槍\",
    \"jp\": \"\",
    \"kr\": \"우리는 Bangna에서 삼촌 총을 사랑합니다\"
  },
  \"shop_types\": [
    \"OFFLINE\",
    \"ONLINE\"
  ],
  \"shop_categories\": [
    \"FOOD\",
    \"SERVICE\"
  ],
  \"shop_addresses\": {
    \"full_address\": \"123/22 ถนนบางนา แขวงบางนา เขตบางนา กทม 10260\",
    \"country\": {
      \"name\": \"Thailand\",
      \"country_code\": \"TH\"
    },
    \"city\": {
      \"name\": \"Bangkok\",
      \"HS_code\": \"BKK\"
    },
    \"district\": \"Bangna\",
    \"postcode\": \"10260\",
    \"geolocation\": \"13.6601781,100.6254328\"
  },
  \"shop_contacts\": [
    {
      \"full_name\": \"คุณปริญญา นามสมมติ\",
      \"phone\": \"0912345678\"
    }
  ],
  \"shop_details\": {
    \"short_description\": \"\",
    \"full_description\": \"\",
    \"open_hours\": {
      \"sun\": \"8.00AM-7:00PM\",
      \"mon\": \"\",
      \"tue\": \"8.00AM-7:00PM\",
      \"wed\": \"8.00AM-7:00PM\",
      \"thu\": \"8.00AM-7:00PM\",
      \"fri\": \"8.00AM-7:00PM\",
      \"sat\": \"8.00AM-7:00PM\"
    },
    \"rating\": {
      \"point\": \"85.33\",
      \"star\": \"4.2\"
    }
  },
  \"shop_status\": \"ACTIVE\"
}", new TypeReference<CreateO2OShopRequest>(){});

        // Set callback and perform API call
        controller.setHttpCallBack(httpResponse);
        try {
        controller.createO2OShop(contentType, body);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
